import type { Metadata } from "next";
import { Inter, Playpen_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const playpenSans = Playpen_Sans({
  subsets: ["latin"],
  variable: "--font-playpen",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={[
          inter.className,
          `${playpenSans.variable} font-sans`,
          "bg-gradient-to-br from-slate-200 to-slate-100 min-h-screen",
        ].join(" ")}
      >
        <div className="p-10">
          <div className="mx-auto max-w-3xl h-full flex flex-col gap-4">
            <div className="flex justify-between font-playpen">
              <div>This is Fine / Episode 2</div>
              <div className="flex gap-5">
                <div>Home</div>
                <div>Share a story</div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-6 mt-8">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
