import type { Metadata } from "next";
import { Inter, Playpen_Sans } from "next/font/google";
import "./globals.css";

import { Provider } from "./_trpc/provider";
import { Navbar } from "~/components/navbar";

const inter = Inter({ subsets: ["latin"] });
const playpenSans = Playpen_Sans({
  subsets: ["latin"],
  variable: "--font-playpen",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={[
          inter.className,
          `${playpenSans.variable} font-sans`,
          "min-h-screen",
        ].join(" ")}
        style={{
          backgroundImage: `url(https://www.transparenttextures.com/patterns/back-pattern.png)`,
        }}
      >
        <Provider>
          <div className="p-10">
            <div className="mx-auto max-w-3xl h-full flex flex-col gap-4">
              <Navbar />

              <div className="grid grid-cols-2 gap-x-6 gap-y-14 mt-12">
                {children}
              </div>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
